services:
  haxbot:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../src:/app/src
      - ../typings:/app/typings
      - ../.env:/app/.env
    environment:
      - HAXBOT_CI=true
